selected_model: "custom_cnn_cifar"  # nfnet / custom_cnn_imgnet
select_dataset_type: "cifar10"  # image_net_1k
epochs: 20
is_local: true
use_optimizations: true
similarity_method: "sbert"  # bert, sbert, nltk
imagenet_path: '/fscratch/sjaber/imagenet'  # /ds/images/imagenet
initial_num_classes: 2
step_num_classes: 2
perform_inc_training: True
perform_normal_training: False
inc_training_type: "alph" #alph, random, most_diss_first
batch_size: 16
learning_rate: 0.2
inc_decay_type: "inc" # dec, static